### ISSUE TITLE
Change the font color of the paragraph in the card

### ISSUE THREAD

**Issue by iamsaumya** [outline/website#21]
The features section on the website shows features through card. It consists of an h3 and a paragraph. What I observe is that the font colour of both the elements is the same thus I am not able to derive an hierarchy.

It will be great! If we can make the paragraph a little bit greyish so that we can see the hierarchy and skim through it with just reading the key points.

Before:

![www getoutline com_](https://user-images.githubusercontent.com/40148448/118328577-a1533600-b523-11eb-91b7-5b831e59ad73.png)

After: 

![www getoutline com_ (1)](https://user-images.githubusercontent.com/40148448/118328658-a617ea00-b523-11eb-938b-f1405a316974.png)
 
I used #5E6573.

**Comment by iamsaumya** [comment]
@tommoor, please let me know your thoughts on this.

**Comment by tommoor** [comment]
Works for me, I think it's a good improvement 👍
