### ISSUE TITLE
Mobile menu display bug

### ISSUE THREAD

**Issue by tddostu** [outline/website#35]
When opening the menu on mobile, it seems to be 'behind' the page header/title (z-index issue I assume). This doesn't happen on the homepage, but on many other pages [see screenshot attached].
![IMG_5136](https://user-images.githubusercontent.com/36751136/144551910-2b35f598-d259-4de8-afec-7d907df489bf.png)

**Comment by tommoor** [comment]
closed by d28c06d81e9c63f1109f471d180fb8ca9965fe0a
